export const SEARCH_YOUTUBE_REQUEST = 'SEARCH_YOUTUBE_REQUEST';
export const SEARCH_YOUTUBE_SUCCESS = 'SEARCH_YOUTUBE_SUCCESS';
export const SEARCH_YOUTUBE_FAILURE = 'FAILURE_SEARCH_YOUTUBE';

export const FETCH_SUGGESTIONS_REQUEST = 'FETCH_SUGGESTIONS_REQUEST';
export const FETCH_SUGGESTIONS_SUCCESS = 'FETCH_SUGGESTIONS_SUCCESS';
export const FETCH_SUGGESTIONS_FAILURE = 'FETCH_SUGGESTIONS_FAILURE';

export const SAVE_VIDEO = 'SAVE_VIDEO';
export const REMOVE_VIDEO = 'REMOVE_VIDEO';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
export const NOOP = 'NOOP';
export const SET_SLIDER_VALUE = 'SET_SLIDER_VALUE';
export const FILTER_VIDEOS = 'FILTER_VIDEOS';
